# Generated by Django 3.1.7 on 2021-03-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Person',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('name', models.CharField(max_length=30)),
    #             ('email', models.EmailField(blank=True, max_length=254)),
    #             ('location', models.CharField(blank=True, max_length=100)),
    #         ],
    #     ),
    # ]
